import Head from 'next/head';
import Layout from '../components/layout';
import { useEffect } from 'react';
import { useRouter } from "next/router";
import { useSelector } from 'react-redux';
import { ThreeDots } from 'react-loader-spinner';
import Holiday from '../components/Holiday';
import { getMyselfData } from '../redux/slices/auth/authSlice'
import { useDispatch } from 'react-redux'

export default function Home() {
  const router = useRouter();
  const dispatch = useDispatch();
  const isAuthenticated = useSelector(state => state.authentication.isAuthenticated)

  useEffect(()=>{
    if (!isAuthenticated) {
      router.push('/login');
    }
  }, [isAuthenticated, router])

  useEffect(()=>{
    dispatch(getMyselfData())
  },[])

  return (
    <div>
      {isAuthenticated ?
          <div>
          <Head>
            <title>Holiday Planner</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Holiday />
        </div> 
       : 
      <div className="flex items-center justify-center mt-96">
          <ThreeDots
            height="90"
            width="90"
            radius="8"
            color="#4fa94d"
            ariaLabel="three-dots-loading"
            wrapperStyle={{}}
            wrapperClassName=""
            visible={true}
          />
        </div>
      }
    </div>
  )


}

Home.getLayout = (page) => <Layout>{page}</Layout>

